### ISSUE TITLE
Add fun/tricky/ uncommon programs

### ISSUE THREAD

**Issue by ayushs1ngh** [ayushs1ngh/Fun-and-Tricky-Programs#1]
Add a PR with any tricky or uncommon coding problem.

Add coding problems and solutions in the respective language folder. if that language folder doesn't exist then create it.
Check other folders in Java or C/CPP how it is done in the rest of the file.

E.g
Add a folder in the Java folder with the Name of Problem Title.
Inside that folder add the solution ProblemTitle.java and a README.md
Make sure the class name is ProblemTitle that is the name of the file.
README.md must contain a detailed description of the problem with the test cases or example input/output.

**Comment by afflato** [comment]
Added Dining Philosopher problem under Java. Take a look at PR #17.

**Comment by afflato** [comment]
Added nQueen an instance of Backtracking under Java. Take a look at PR#18
